### ISSUE TITLE
Structural Feature Extraction

### ISSUE THREAD

**Issue by Agnivo** [biswajitsc/LaSer#17]
Extract features based on Algebraic structures and pattern matching and also replace variables, operators by certain placeholders. So, x + y matches with a + b and e ^ (x + ab) matches with e ^ (c) with a low probability.

**Comment by Agnivo** [comment]
e ^ (a + b) should match with d ^ c

**Comment by biswajitsc** [comment]
Are we going to do this in the baseline ?

For e^(x+y) to match d^c, we need to normalize the variables. Is this given in the thesis paper ?

**Comment by biswajitsc** [comment]
Not required now.
