### ISSUE TITLE
Task: Parse using MathML

### ISSUE THREAD

**Issue by biswajitsc** [biswajitsc/LaSer#4]
Parse the formulae using mathml and save them in a properly formed xml file. Keep looking at the parsed formula to get any interesting ideas.

Close this issue when parsing is done.

**Comment by prithm** [comment]
I will be doing this.

**Comment by anuraganand** [comment]
No, I'll do it.

Sent from my Windows Phone

**Comment by prithm** [comment]
we have done it.

**Comment by prithm** [comment]
we have done it.
